"""initial

Revision ID: e95c7b880161
Revises: 
Create Date: 2024-02-04 13:45:23.463552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import map_storage

# revision identifiers, used by Alembic.
revision: str = 'e95c7b880161'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_layers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('zoom', sa.Float(), nullable=False),
    sa.Column('has_images', sa.Boolean(), nullable=False),
    sa.Column('has_surf_features', sa.Boolean(), nullable=False),
    sa.Column('surf_min_hessian', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_tiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_long', sa.Float(), nullable=False),
    sa.Column('nw_lat', sa.Float(), nullable=False),
    sa.Column('nw_long', sa.Float(), nullable=False),
    sa.Column('ne_lat', sa.Float(), nullable=False),
    sa.Column('ne_long', sa.Float(), nullable=False),
    sa.Column('se_lat', sa.Float(), nullable=False),
    sa.Column('se_long', sa.Float(), nullable=False),
    sa.Column('sw_lat', sa.Float(), nullable=False),
    sa.Column('sw_long', sa.Float(), nullable=False),
    sa.Column('azimuth', sa.Float(), nullable=False),
    sa.Column('map_layer_id', sa.Integer(), nullable=True),
    sa.Column('img', map_storage.features.shared.custom_db_types.NumpyArray(), nullable=True),
    sa.Column('surf_keypoints', map_storage.features.shared.custom_db_types.SURFKeyPoints(), nullable=True),
    sa.Column('surf_descriptors', map_storage.features.shared.custom_db_types.NumpyArray(), nullable=True),
    sa.ForeignKeyConstraint(['map_layer_id'], ['map_layers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coordinates', 'map_tiles', ['center_lat', 'center_long'], unique=False)
    op.create_index('idx_map_layer_id', 'map_tiles', ['map_layer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_map_layer_id', table_name='map_tiles')
    op.drop_index('idx_coordinates', table_name='map_tiles')
    op.drop_table('map_tiles')
    op.drop_table('map_layers')
    # ### end Alembic commands ###
