from setuptools import setup

setup(
    name="map_storage",
    packages=["map_storage"],
    version="0.0.1",
    description="Map storage package dedicated for importing map layers from external providers and querying loaded tiles with sdk",
    url="https://github.com/VynnykV/MapStorage",
    author="Vitalii Vynnyk",
    author_email="vitalik.vinnik.05@gmail.com",
    license="MIT",
    classifiers=[
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.11",
        "Operating System :: OS Independent",
    ],
    install_requires=[
        "aiohttp==3.9.1",
        "aiosignal==1.3.1",
        "alembic==1.13.1",
        "annotated-types==0.6.0",
        "anyio==3.7.1",
        "async-timeout==4.0.3",
        "asyncpg==0.29.0",
        "attrs==23.2.0",
        "click==8.1.7",
        "exceptiongroup==1.2.0",
        "frozenlist==1.4.1",
        "geographiclib==2.0",
        "geopy==2.4.1",
        "h11==0.14.0",
        "idna==3.6",
        "Mako==1.3.0",
        "MarkupSafe==2.1.3",
        "multidict==6.0.4",
        "numpy==1.26.3",
        "pydantic==2.5.3",
        "pydantic-settings==2.1.0",
        "pydantic_core==2.14.6",
        "python-dotenv==1.0.0",
        "sniffio==1.3.0",
        "SQLAlchemy==2.0.24",
        "typing_extensions==4.9.0"
    ],
    extras_require={ },
    python_requires=">=3.11",
)