"""add import type column

Revision ID: 57f9c6e9f6d9
Revises: 7ab865de2dba
Create Date: 2024-05-02 12:20:10.924035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f9c6e9f6d9'
down_revision: Union[str, None] = '7ab865de2dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_layers', sa.Column('import_type', sa.String(length=20), server_default='rectangle', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_layers', 'import_type')
    # ### end Alembic commands ###
