"""added_img_shape

Revision ID: 7ab865de2dba
Revises: de784a743907
Create Date: 2024-03-10 10:51:50.148918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab865de2dba'
down_revision: Union[str, None] = 'de784a743907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_tiles', sa.Column('img_width', sa.Integer(), server_default='0', nullable=False))
    op.add_column('map_tiles', sa.Column('img_height', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_tiles', 'img_height')
    op.drop_column('map_tiles', 'img_width')
    # ### end Alembic commands ###
