"""fast_keypoints

Revision ID: de784a743907
Revises: 445d6dac1fab
Create Date: 2024-03-05 19:06:19.439652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import map_storage


# revision identifiers, used by Alembic.
revision: str = 'de784a743907'
down_revision: Union[str, None] = '445d6dac1fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_layers', sa.Column('has_fast_features', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('map_layers', sa.Column('fast_threshold', sa.Float(), nullable=True))
    op.add_column('map_layers', sa.Column('fast_nonmax_suppression', sa.Boolean(), nullable=True))
    op.add_column('map_layers', sa.Column('fast_type', sa.Integer(), nullable=True))
    op.add_column('map_tiles', sa.Column('fast_keypoints', map_storage.features.shared.custom_db_types.NumpyArray(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_tiles', 'fast_keypoints')
    op.drop_column('map_layers', 'fast_type')
    op.drop_column('map_layers', 'fast_nonmax_suppression')
    op.drop_column('map_layers', 'fast_threshold')
    op.drop_column('map_layers', 'has_fast_features')
    # ### end Alembic commands ###
